#!/bin/bash

ENV_NAME="somax310"

SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LOCAL_PATH="${SCRIPT_DIRECTORY}/../../../python/somax/somax_server.py"

# Use conda run to execute inside the right environment
conda run --no-capture-output -n "$ENV_NAME" python "${LOCAL_PATH}"